services:
  # PostgreSQL service
  postgres:
    image: postgres:latest
    container_name: my_custom_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # PgAdmin service
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_custom_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - postgres
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: my_custom_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  # Redis service
  redis:
    image: redis:latest
    container_name: my_custom_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  mongo_data:
  redis_data: